#!/bin/bash

PROCESS_NAME="manage_my_process"
PROCESS_PATH="/path/to/manage_my_process"  # Update this path to the actual location of manage_my_process

start() {
if pgrep -f $PROCESS_NAME > /dev/null
then
echo "$PROCESS_NAME is already running"
else
nohup $PROCESS_PATH &> /dev/null &
echo "$PROCESS_NAME started"
fi
}
stop() {
if pgrep -f $PROCESS_NAME > /dev/null
then
pkill -f $PROCESS_NAME
echo "$PROCESS_NAME stopped"
else
echo "$PROCESS_NAME is not running"
fi
}
restart() {
stop
start
}
case "$1" in
start)
start
;;
stop)
stop
;;
restart)
restart
;;
*)
echo "Usage: $0 {start|stop|restart}"
exit 1
;;
esac
